# Generated by Django 4.2.3 on 2023-08-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
