# Generated by Django 4.1.3 on 2023-08-08 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_question_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='list',
            field=models.ForeignKey(blank=True, default='List1', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.list'),
        ),
    ]
