# Generated by Django 4.1.3 on 2023-08-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_topic_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='notes',
            new_name='note',
        ),
    ]
