# Generated by Django 4.2.3 on 2023-08-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
