# Generated by Django 4.2.3 on 2023-07-20 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WTopic',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WQLinks',
            fields=[
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='websiteContent.wquestion')),
                ('yt_link', models.CharField(max_length=200)),
                ('striver_link', models.CharField(max_length=200)),
                ('leetcode_link', models.CharField(max_length=200)),
                ('gfg_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='wquestion',
            name='topic',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='websiteContent.wtopic'),
        ),
        migrations.CreateModel(
            name='WApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteContent.wquestion')),
            ],
        ),
    ]
