# Generated by Django 4.1.3 on 2023-08-08 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WList',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('last_visited', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WQLinks',
            fields=[
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='websiteContent.wquestion')),
                ('youtube_link', models.CharField(blank=True, max_length=200, null=True)),
                ('striver_link', models.CharField(blank=True, max_length=200, null=True)),
                ('leetcode_link', models.CharField(blank=True, max_length=200, null=True)),
                ('other_link', models.CharField(blank=True, max_length=200, null=True)),
                ('gfg_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WTopic',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('list', models.ForeignKey(blank=True, default='List1', null=True, on_delete=django.db.models.deletion.CASCADE, to='websiteContent.wlist')),
            ],
        ),
        migrations.AddField(
            model_name='wquestion',
            name='topic',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='websiteContent.wtopic'),
        ),
        migrations.CreateModel(
            name='WApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteContent.wquestion')),
            ],
        ),
        migrations.CreateModel(
            name='WLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('blank', models.BooleanField(default=False)),
                ('approach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteContent.wapproach')),
            ],
            options={
                'unique_together': {('line_number', 'approach')},
            },
        ),
    ]
