# Generated by Django 4.1.3 on 2023-07-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteContent', '0002_wlist_wtopic_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wqlinks',
            name='yt_link',
        ),
        migrations.AddField(
            model_name='wqlinks',
            name='other_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wqlinks',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wqlinks',
            name='gfg_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wqlinks',
            name='leetcode_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wqlinks',
            name='striver_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
