# Generated by Django 4.1.3 on 2023-07-31 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteContent', '0003_remove_wqlinks_yt_link_wqlinks_other_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtopic',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteContent.wlist'),
        ),
    ]
