# Generated by Django 4.2.3 on 2023-08-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteContent', '0007_alter_wtopic_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wlist',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='wquestion',
            name='topic',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='websiteContent.wtopic'),
        ),
        migrations.CreateModel(
            name='WLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('blank', models.BooleanField(default=False)),
                ('approach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteContent.wapproach')),
            ],
            options={
                'unique_together': {('line_number', 'approach')},
            },
        ),
    ]
